<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC" ignored="0" name="Test" tests="8" failures="1" timestamp="2020-04-26T02:07:39 ICT" time="135.735" errors="0">
  <testcase name="TO_Sort_First_Name" time="46.734" classname="KarrosTechPJ.Karros.RequestAccess.TC_Sort_First_Name"/>
  <testcase name="TO_API_001" time="5.282" classname="KarrosTechPJ.Karros.API.TC_PostAPI"/>
  <testcase name="TO_API_002" time="1.891" classname="KarrosTechPJ.Karros.API.TC_PostAPI"/>
  <testcase name="TO_API_003" time="7.314" classname="KarrosTechPJ.Karros.API.TC_PostAPI"/>
  <testcase name="TO_API_004" time="2.908" classname="KarrosTechPJ.Karros.API.TC_PostAPI"/>
  <testcase name="TO_API_005" time="1.823" classname="KarrosTechPJ.Karros.API.TC_PostAPI"/>
  <testcase name="TO_API_006" time="26.711" classname="KarrosTechPJ.Karros.API.TC_PostAPI"/>
  <testcase name="TO_Request_Status" time="5.7" classname="KarrosTechPJ.Karros.Filters.TC_Request_Status">
    <failure type="java.lang.AssertionError" message="expected [3] but found [9]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [9]
at KarrosTechPJ.Karros.Filters.TC_Request_Status.TO_Request_Status(TC_Request_Status.java:64)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TO_Request_Status -->
</testsuite> <!-- Test -->
