<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC" ignored="0" name="Test" tests="3" failures="1" timestamp="2020-04-25T18:50:31 ICT" time="93.692" errors="0">
  <testcase name="TO_Sort_First_Name" time="47.277" classname="KarrosTechPJ.Karros.RequestAccess.TC_Sort_First_Name"/>
  <testcase name="TO_PostAPI" time="5.556" classname="KarrosTechPJ.Karros.API.TC_PostAPI"/>
  <testcase name="TO_Request_Status" time="5.735" classname="KarrosTechPJ.Karros.Filters.TC_Request_Status">
    <failure type="java.lang.AssertionError" message="expected [3] but found [9]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [9]
at KarrosTechPJ.Karros.Filters.TC_Request_Status.TO_Request_Status(TC_Request_Status.java:64)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TO_Request_Status -->
</testsuite> <!-- Test -->
